name = "website"
main = "code.js"
compatibility_date = "2023-11-21"

# 开发环境配置
workers_dev = true

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "my_soul_refuel_db"
database_id = "09defb11-33ab-435e-a028-76b25fc1ff5d"

# 可选：添加环境变量配置
[vars]
ENVIRONMENT = "development"

# 可选：添加开发环境配置
[dev]
port = 8787
local_protocol = "http"

# 可选：配置资源限制
[limits]
cpu_ms = 50
memory_mb = 128