
name = "soul-refueling-station"
main = "code.js"
compatibility_date = "2024-12-26"

[[d1_databases]]
binding = "DB"
database_name = "my_soul_refuel_db"
database_id = "09defb11-33ab-435e-a028-76b25fc1ff5d"

[[static_assets]]
pattern = "/static/sounds/*"
path = "./public/sounds"

[dev]
port = 8787
local_protocol = "http"

[limits]
cpu_ms = 50
memory_mb = 128

[vars]
ENVIRONMENT = "production"
